# Generated by Django 3.2.5 on 2021-08-02 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('text', models.CharField(max_length=256)),
                ('auction_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auc_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
