# Generated by Django 3.2.5 on 2021-08-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(default=1, upload_to='documents'),
            preserve_default=False,
        ),
    ]
