# Generated by Django 3.2.5 on 2021-08-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210802_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='title',
            new_name='name',
        ),
    ]
