# Generated by Django 3.2.5 on 2021-08-03 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210803_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_auction',
        ),
    ]
