# Generated by Django 3.2.5 on 2021-08-03 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210803_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='auctions.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auctions_comment', to='auctions.auction'),
            preserve_default=False,
        ),
    ]
