# Generated by Django 3.2.5 on 2021-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auction_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid',
            field=models.IntegerField(default=0),
        ),
    ]
