# Generated by Django 3.2.5 on 2021-08-06 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_bid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_auc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auctions_watch', to='auctions.auction')),
                ('watch_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_watch', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
