# Generated by Django 3.2.5 on 2021-08-07 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auction_last_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_belong', to='auctions.user'),
            preserve_default=False,
        ),
    ]
